// Auto-generated dialogue options for non-branching scenes
// Generated by scripts/generate-dialogue-options.js

const DIALOGUE_OPTIONS = {
    "branch1_005": {
        "preface": "(to himself)",
        "options": ["Huh. Didn't realize this thing was so durable. Five years and still going strong.","That's odd... it should've cracked from that fall. Lucky, I guess."]
    },
    "branch1_013": {
        "preface": "(surprised)",
        "options": ["When did that start? I didn't even hear it begin.","Strange... it was clear just a moment ago."]
    },
    "branch1_017": {
        "preface": "(pulling blankets tighter)",
        "options": ["Storm came out of nowhere...","This weather is completely wrong for this time of year..."]
    },
    "branch1_019": {
        "preface": "(sitting up)",
        "options": ["What the hell?","Not again... what now?"]
    },
    "branch2_001": {
        "preface": "(calling toward the window)",
        "options": ["Who's there?","Show yourself!"]
    },
    "branch2_003": {
        "preface": "(climbing through the window with forced cheerfulness)",
        "options": ["Sorry! Didn't mean to scare you. I knocked on the front door but you didn't answer.","Surprise! I know, I know, should've called first. But your doorbell seems broken."]
    },
    "branch2_004": {
        "preface": "(confused and slightly annoyed)",
        "options": ["Marzia? You nearly gave me a heart attack. Why didn't you just call first?","Jesus, Marzia! What are you doing climbing through my window?"]
    },
    "branch2_005": {
        "preface": "(forced laugh)",
        "options": ["You know how you get on difficult days. I was worried you might not pick up.","I tried calling. Three times. You didn't answer, so I got concerned."]
    },
    "branch2_008": {
        "options": ["I was making tea when I heard something outside. The whole setup just... fell over.","Not sure. One moment everything was fine, the next... this mess."]
    },
    "branch2_009": {
        "preface": "(too quickly)",
        "options": ["Probably the wind. It's picking up out there.","Must've been a draft. These old houses are full of them."]
    },
    "branch2_012": {
        "options": ["You seem nervous tonight. Everything okay at the hospital?","Something's wrong. You're acting strange. What's going on?"]
    },
    "branch2_013": {
        "preface": "(defensive)",
        "options": ["I'm fine. Just tired. Long shift.","Nothing. Why would something be wrong? I'm perfectly fine."]
    },
    "branch2_014": {
        "options": ["It's Thursday. You don't usually work Thursdays.","Thursday's your day off. You told me that yourself."]
    },
    "branch2_016": {
        "preface": "(recovering)",
        "options": ["Emergency call-in. Dr. Hassan was sick.","Schedule change. They needed extra hands in the ER."]
    },
    "scene_002": {
        "preface": "(checking phone)",
        "options": ["Unknown number... at this hour?","Who could be calling this late?"]
    },
    "scene_004": {
        "options": ["Hello?","Yes, this is Rumi speaking."]
    },
    "scene_006": {
        "preface": "(suddenly alert)",
        "options": ["Yes... who is this?","Speaking. What's happened?"]
    },
    "scene_009": {
        "options": ["And?","Tell me everything. Now."]
    },
    "scene_014": {
        "preface": "(whispering)",
        "options": ["No... no, this can't be...","There must be some mistake... this isn't her..."]
    },
    "scene_016": {
        "preface": "(breaking down)",
        "options": ["She was supposed to come home tonight... we were going to... we were going to...","We had plans for tomorrow... I was waiting up for her... she promised..."]
    },
    "scene_019": {
        "preface": "(panicked)",
        "options": ["Baba, where's Jannat? Where is she?","Father, please tell me it was just a nightmare. Where is she?"]
    },
    "scene_021": {
        "preface": "(screaming)",
        "options": ["NO! She can't be gone! She can't be!","This isn't happening! Tell me this isn't real!"]
    },
    "scene_025": {
        "preface": "(to the photo)",
        "options": ["Three years, Jannat. Three years and I still can't... I can't let you go.","It's been three years, and the pain hasn't dulled even a little. I miss you so much."]
    },
    "scene_031": {
        "preface": "(startled)",
        "options": ["How did that happen?","What the hell...?"]
    },
    "sub_branch1_1_001": {
        "preface": "(backing away, frightened)",
        "options": ["This is impossible... this happened hours ago... I cleaned this up...","I already fixed this... how is this happening again?"]
    },
    "sub_branch1_1_004": {
        "preface": "(whisper)",
        "options": ["No... it can't be...","Jannat? That's impossible..."]
    },
    "sub_branch1_1_007": {
        "preface": "(approaching cautiously)",
        "options": ["Jannat? How... how are you here?","This can't be real... you're dead..."]
    },
    "sub_branch1_1_011": {
        "preface": "(shaking head frantically)",
        "options": ["No. Marzia did this. It was Marzia in the car accident.","I didn't do this. You died in a crash. It wasn't my fault."]
    },
    "sub_branch1_1_012": {
        "preface": "(hollow laugh)",
        "options": ["Is that what you've told yourself for three years? Is that the lie you've been living?","Three years of denial. Three years of believing the story she fed you."]
    },
    "sub_branch1_1_016": {
        "options": ["I can't do this anymore, Rumi. Your paranoia, your jealousy - it's destroying us. I need space.","This has to stop. Your constant accusations, your suspicions - I can't breathe. I need to leave for a while."]
    },
    "sub_branch1_1_017": {
        "options": ["You're leaving me for him, aren't you? For that doctor you work with?","Don't lie to me! I know you're having an affair with Dr. Nabil!"]
    },
    "sub_branch1_1_018": {
        "options": ["There's nothing between me and Dr. Nabil! This is exactly what I'm talking about - these delusions!","For God's sake, he's my obstetrician! That's all! You're being irrational!"]
    },
    "sub_branch1_1_021": {
        "preface": "(screaming)",
        "options": ["Those texts were about our baby, you idiot! I'm pregnant! He's my obstetrician! I was going to surprise you on your birthday!","Stop! Listen to me! I'm carrying your child! Dr. Nabil is helping me with the pregnancy! I was planning to tell you this weekend!"]
    },
    "sub_branch1_1_023": {
        "preface": "(present, backing away)",
        "options": ["No... that's not what happened...","Stop showing me this... this isn't real..."]
    },
    "sub_branch1_1_025": {
        "preface": "(present, calmly)",
        "options": ["You beat me to death. You beat our unborn child to death. And then you called Marzia to help you cover it up.","Twelve blows to the head. You killed me and our baby. Then Marzia helped you stage the accident."]
    },
    "sub_branch1_1_026": {
        "preface": "(collapsing)",
        "options": ["I... I remember now. The blood. The sound when I...","Oh God... it's all coming back... what have I done?"]
    },
    "sub_branch1_1_027": {
        "options": ["You killed two people that night, Rumi. Me and our son.","A wife and an unborn child. That's what your jealous rage cost."]
    },
    "sub_branch1_1_028": {
        "preface": "(sobbing)",
        "options": ["What have I done? What have I become?","I'm a monster... I killed you... I killed our baby..."]
    },
    "sub_branch1_1_030": {
        "options": ["She's been medicating you for three years. Not for grief - to control your violent episodes. To keep you from remembering what you did.","Every pill she gave you was designed to suppress the truth. To keep you docile and forgetful."]
    },
    "sub_branch1_1_033": {
        "options": ["She's here to keep the monster contained. The question is: what will you do with the truth?","Your jailer has arrived. Will you submit to her control again, or will you face what you've done?"]
    },
    "sub_branch1_1_035": {
        "options": ["Rumi, you haven't been taking your medication, have you?","Oh no... you stopped taking the pills, didn't you? How long has it been?"]
    },
    "sub_branch1_1_036": {
        "options": ["I remember everything, Marzia.","The drugs are wearing off. I can see it all now."]
    },
    "sub_branch1_1_038": {
        "options": ["The hammer. The blood. The sound her skull made when I... I killed her. I killed my pregnant wife.","I murdered Jannat. Beat her to death with a hammer while she begged for mercy. She was carrying my child."]
    },
    "sub_branch1_1_039": {
        "preface": "(gently)",
        "options": ["You're having an episode, Rumi. Let me help you.","These are false memories, Rumi. The trauma is creating delusions. Take your medication."]
    },
    "sub_branch1_1_040": {
        "preface": "(roaring)",
        "options": ["Stop LYING! I saw it! Jannat showed me the truth!","NO MORE LIES! I remember what I did to her!"]
    },
    "sub_branch1_1_042": {
        "preface": "(preparing syringe)",
        "options": ["These delusions - you need your medication.","Rumi, please. You're seeing things that aren't there. Let me help you."]
    },
    "sub_branch1_1_043": {
        "preface": "(grabbing lamp, hurling it)",
        "options": ["They're not delusions! I killed her because I thought she was cheating. But she wasn't. She was pregnant with my child.","I murdered my wife! My pregnant wife! And you helped me hide it!"]
    },
    "sub_branch1_1_044": {
        "preface": "(clinical demeanor cracking)",
        "options": ["Yes. She was. And you've spent three years blocking it out because your mind couldn't handle the guilt.","You're right. I helped you cover it up. I've been keeping you sedated so you wouldn't remember."]
    },
    "sub_branch1_1_045": {
        "options": ["Without the medication, I remember the truth. That I'm a murderer. That you helped me cover it up.","The fog is lifting. I can see clearly now. I killed her, and you made me forget."]
    },
    "sub_branch1_1_046": {
        "preface": "(tears streaming)",
        "options": ["I had no choice. I loved you. I thought I could keep you stable, keep you from hurting anyone else.","What was I supposed to do? Turn you in? I couldn't. So I've been managing you, controlling you, trying to keep you safe."]
    },
    "sub_branch1_1_047": {
        "options": ["I should have gone to the police. But I'd already helped move the body. I was complicit. So I convinced myself that keeping you medicated was the best I could do.","The moment I helped you stage that accident, I became an accomplice. Prison or this - those were my choices."]
    },
    "sub_branch1_1_048": {
        "options": ["All these years, I thought you were my friend.","You pretended to care about me while you were really just my keeper."]
    },
    "sub_branch1_1_049": {
        "options": ["I was your jailer. Your psychiatric nurse. Because you destroyed your conscience with the same hammer you used on Jannat's skull.","I've been your warden for three years. Someone had to control the monster you became."]
    },
    "sub_branch1_1_051": {
        "options": ["You should have let me face justice!","I deserved prison! You had no right to decide!"]
    },
    "sub_branch1_1_052": {
        "preface": "(choking)",
        "options": ["Rumi, please - this isn't you, it's the illness!","Stop... you're not a killer... don't prove me wrong..."]
    },
    "sub_branch1_1_053": {
        "options": ["No. This is exactly who I am. A murderer.","I killed once. What's one more life?"]
    },
    "sub_branch1_1_054": {
        "preface": "(appearing beside him)",
        "options": ["This won't bring me back. This won't bring our baby back.","More blood won't wash away your sins, Rumi."]
    },
    "sub_branch1_1_056": {
        "options": ["She tried to help you, in her way. Killing her won't make things right.","Her methods were wrong, but her intentions... Let her call the police. Face your punishment properly."]
    },
    "sub_branch1_1_057": {
        "preface": "(releasing Marzia)",
        "options": ["Get out. Get out and call the police. Tell them I'm confessing to the murder of Jannat.","Leave. Now. And tell the authorities everything. I'm ready to face what I've done."]
    },
    "sub_branch1_1_059": {
        "preface": "(grabbing kitchen knife)",
        "options": ["GET OUT! Call the police, or I swear I'll finish what I started.","LEAVE! Bring the police or I won't be responsible for what happens next!"]
    },
    "sub_branch1_1_061": {
        "options": ["What happens now?","Is this what you wanted? Justice?"]
    },
    "sub_branch1_1_062": {
        "options": ["Now you face the truth.","Now you pay for what you've done."]
    },
    "sub_branch1_1_064": {
        "options": ["They'll take you away. Prison, or a psychiatric facility. Is that justice enough?","You'll spend years behind bars, or locked in a mental ward. Will that balance the scales?"]
    },
    "sub_branch1_1_066": {
        "options": ["No. It's not enough.","Nothing could ever be enough. But I have to try."]
    },
    "sub_branch1_1_067": {
        "options": ["What would be enough?","Show me, then. Show me your remorse."]
    },
    "sub_branch1_1_068": {
        "preface": "(raising knife)",
        "options": ["The same pain I inflicted. The same destruction.","Blood for blood. Pain for pain."]
    },
    "sub_branch1_1_071": {
        "preface": "(sobbing, cutting again)",
        "options": ["I'm sorry... I'm so sorry...","Forgive me... please forgive me..."]
    },
    "sub_branch1_1_073": {
        "preface": "(calmly to officers)",
        "options": ["I killed my wife. Three years ago. I beat her to death with a hammer because I thought she was unfaithful. She was pregnant with my child.","My name is Rumi Bin Imran. Three years ago, I murdered my pregnant wife in a fit of jealous rage. I'm ready to confess everything."]
    },
    "sub_branch1_1_075": {
        "options": ["No. I need to confess now.","Let me bleed. I need to tell you what I did first."]
    },
    "sub_branch1_1_077": {
        "preface": "(to her)",
        "options": ["I'm sorry. I'm so sorry.","Can you ever forgive me?"]
    },
    "sub_branch1_1_080": {
        "options": ["Will you be charged?","What about you? What will happen to you?"]
    },
    "sub_branch1_1_081": {
        "options": ["Accessory after the fact. I'll lose my license. Serve some time.","They're offering a plea deal. Reduced sentence in exchange for testimony. I'll never practice medicine again."]
    },
    "sub_branch1_1_082": {
        "options": ["I'm sorry. For dragging you into this.","None of this would have happened if I'd been a better man. I'm sorry."]
    },
    "sub_branch1_1_085": {
        "options": ["Do you think she can rest now? Now that the truth is known?","Is Jannat at peace now? Does she know justice is being served?"]
    },
    "sub_branch1_1_086": {
        "options": ["Jannat is gone, Rumi. The only ghosts are the ones in your mind.","There are no ghosts, Rumi. Only guilt. Only memories. And those will haunt you forever."]
    },
    "sub_branch1_1_088": {
        "options": ["Are you still here to torment me?","Why haven't you left? Haven't I suffered enough?"]
    },
    "sub_branch1_1_089": {
        "options": ["No. I'm here to help you heal. The truth is out. Justice is being served.","I'm not here to punish you anymore. You're doing that well enough yourself."]
    },
    "sub_branch1_1_090": {
        "options": ["Will you ever forgive me?","Can someone like me even deserve forgiveness?"]
    },
    "sub_branch1_1_091": {
        "preface": "(touching his cheek)",
        "options": ["Forgiveness isn't what you need from me. You need to forgive yourself enough to face your illness, to get the help you've needed all along.","I can't give you absolution. But I can tell you this: get real help. Face your demons. That's the only path forward."]
    },
    "sub_branch1_1_093": {
        "preface": "(beginning to fade)",
        "options": ["You live with what you've done. You carry it. That's your sentence. That's your penance.","Then you wake up every day and choose to be better than the monster you were. Every single day, for the rest of your life."]
    },
    "sub_branch1_2_001": {
        "preface": "(backing away, frightened)",
        "options": ["This is impossible... this happened hours ago...","I already cleaned this... what's happening?"]
    },
    "sub_branch1_2_003": {
        "preface": "(approaching window cautiously)",
        "options": ["What the hell is going on?","Something's very wrong here..."]
    },
    "sub_branch1_2_006": {
        "preface": "(turning slowly)",
        "options": ["Jannat?","That voice... it can't be..."]
    },
    "sub_branch1_2_008": {
        "preface": "(approaching cautiously)",
        "options": ["Jannat? How... how are you here?","This can't be real... you're dead..."]
    },
    "sub_branch1_2_009": {
        "preface": "(hollow, echoing quality)",
        "options": ["I've been waiting for you to see me, Rumi. Really see me.","Three years I've waited in the darkness for you to open your eyes."]
    },
    "sub_branch1_2_010": {
        "options": ["I don't understand. You died in a car accident.","They said it was a crash. That you died instantly."]
    },
    "sub_branch1_2_011": {
        "options": ["Did I? Or is that just what she wanted everyone to believe?","Is that what Marzia told you? That I died in a simple accident?"]
    },
    "sub_branch1_2_014": {
        "preface": "(voice-over)",
        "options": ["I was calling you. I had discovered something terrible about Marzia, and I was trying to warn you.","I tried to reach you. I'd found evidence of what she was doing to you. But you never answered."]
    },
    "sub_branch1_2_016": {
        "options": ["But you didn't answer.","The phone rang and rang. And while it rang, she came for me."]
    },
    "sub_branch1_2_018": {
        "preface": "(horrified)",
        "options": ["What did you discover?","What had she done? Tell me!"]
    },
    "sub_branch1_2_019": {
        "options": ["She had been drugging you, Rumi. For months. Small doses that made you more susceptible to suggestion.","Pills in your coffee. Powder in your food. Chemicals that made your mind malleable to her lies."]
    },
    "sub_branch1_2_021": {
        "options": ["She told me she had been slowly poisoning your mind against me. Planting doubts about my faithfulness so that when she struck, you would believe any story.","For months she whispered in your ear. Showed you 'evidence' of affairs that never happened. Made you doubt everything about our love."]
    },
    "sub_branch1_2_022": {
        "options": ["This is horrible. Why would she do this?","Why? We were happy. We loved each other."]
    },
    "sub_branch1_2_023": {
        "options": ["Because she discovered I was pregnant.","Because I was carrying your child. The one thing she could never give you."]
    },
    "sub_branch1_2_025": {
        "options": ["I was awake for part of it. The first few blows didn't kill me immediately. I felt her dragging my body, felt the gravel scraping against my exposed brain tissue.","Do you want to know the worst part? I was conscious. Paralyzed, but conscious. I felt everything she did to me afterward."]
    },
    "sub_branch1_2_027": {
        "options": ["She took a sledgehammer to what was left of my head. She wanted to make sure no one would ever tell that she had beaten me to death first.","Twenty-three blows with that sledgehammer. I counted every one before I finally died."]
    },
    "sub_branch1_2_028": {
        "preface": "(tears streaming)",
        "options": ["Why? Why would she torture you like this?","What kind of monster does this to an innocent person?"]
    },
    "sub_branch1_2_029": {
        "options": ["Because I was carrying your child, and she couldn't bear anyone else having the family she wanted with you.","Jealousy. Obsession. Love twisted into something monstrous. Take your pick."]
    },
    "sub_branch1_2_031": {
        "options": ["I had just found out that morning. I was so excited. I bought tiny baby shoes to surprise you when you came home.","Three months pregnant. We were going to have a son. I'd already picked out names."]
    },
    "sub_branch1_2_032": {
        "options": ["We were going to have a child?","A baby? We were going to be parents?"]
    },
    "sub_branch1_2_033": {
        "options": ["But when I went to Marzia for a pregnancy checkup, she seemed devastated instead of happy. That's when I started putting pieces together.","I showed her the positive test, expecting congratulations. Instead, I saw murder in her eyes."]
    },
    "sub_branch1_2_035": {
        "options": ["I realized she had been in love with you for years. Photos dating back to childhood, journals about you obsessively, detailed plans for eliminating obstacles.","Her apartment was a shrine to you. Pictures from when you were children. Diary entries spanning decades. She'd been planning this for years."]
    },
    "sub_branch1_2_036": {
        "options": ["She was planning this for a long time?","All those years... she was obsessed with me?"]
    },
    "sub_branch1_2_037": {
        "options": ["For years. My pregnancy was the final trigger that pushed her over the edge.","She was patient. Methodical. But a baby? That she couldn't tolerate."]
    },
    "sub_branch1_2_040": {
        "preface": "(urgent)",
        "options": ["She's here. She's been coming every night since I died, making sure you stay medicated, stay compliant.","Your keeper has arrived. Every night for three years, she's come to poison you."]
    },
    "sub_branch1_2_041": {
        "options": ["Different how?","What's changed? Why tonight?"]
    },
    "sub_branch1_2_042": {
        "options": ["Tonight is the three-year anniversary. She's not here to drug you. She's here to kill you the same way she killed me.","Three years of waiting. Tonight, she finishes what she started. You die the way I died."]
    },
    "sub_branch1_2_044": {
        "preface": "(eerily calm)",
        "options": ["Hello, Rumi. I see you're having trouble sleeping again.","Still awake, my love? That's unfortunate. I was hoping you'd be unconscious for this."]
    },
    "sub_branch1_2_045": {
        "options": ["Three years is long enough to grieve, don't you think? Tonight, you join your beloved wife.","I've been patient. I've given you time to love me. But you're still hers, aren't you? Time to fix that."]
    },
    "sub_branch1_2_046": {
        "options": ["Marzia, what are you doing?","Have you lost your mind? Put those down!"]
    },
    "sub_branch1_2_047": {
        "options": ["I gave you three years to fall in love with me. But you're still as obsessed with that dead bitch as the day I caved her skull in.","Three years of devotion, and you still whisper her name in your sleep. I won't tolerate it anymore."]
    },
    "sub_branch1_2_048": {
        "preface": "(to Rumi)",
        "options": ["She planned this from the beginning. Make you dependent for three years, then when you failed to love her, kill you the same brutal way.","This was always her endgame. Keep you close until she couldn't anymore."]
    },
    "sub_branch1_2_049": {
        "options": ["Just like I beat her to death. I'm going to crush your skull the same way, one savage blow at a time. But I'll make you last longer. She only took twelve hits to die. You're going to take twenty.","I want you to experience what she felt. Every crack of bone. Every splinter of skull. Except you'll suffer longer."]
    },
    "sub_branch1_2_051": {
        "options": ["I want you to know exactly how she died. I want you to experience every moment of agony I put her through.","Each blow will be a lesson. In pain. In betrayal. In what happens when you reject my love."]
    },
    "sub_branch1_2_052": {
        "options": ["You're insane.","You're a monster!"]
    },
    "sub_branch1_2_053": {
        "preface": "(swinging)",
        "options": ["I'm in love! If I can't have you in life, then in death you'll be free from her memory!","Love makes us do terrible things, Rumi! You should understand that better than anyone!"]
    },
    "sub_branch1_2_055": {
        "preface": "(solid, real)",
        "options": ["Not if I have anything to say about it.","You took my life. You won't take his."]
    },
    "sub_branch1_2_057": {
        "options": ["Three years of rage, three years of unfinished business. You think death is the end? You think murder goes unpunished?","Did you really think I'd rest peacefully after what you did to me? To my child?"]
    },
    "sub_branch1_2_059": {
        "options": ["You're not real. You're just his grief-induced hallucination.","Ghosts aren't real! You're a delusion! A trick of his broken mind!"]
    },
    "sub_branch1_2_060": {
        "options": ["Then why are you so afraid?","If I'm not real, why is your hand shaking?"]
    },
    "sub_branch1_2_062": {
        "preface": "(hissing)",
        "options": ["You want to know what it felt like? To have your skull crushed piece by piece while you begged for mercy? To feel your baby die inside you with each blow?","Let me show you what you did to me. Let me return the favor, blow by blow."]
    },
    "sub_branch1_2_063": {
        "preface": "(screaming)",
        "options": ["Stay away from me!","Get back! I'll kill you again!"]
    },
    "sub_branch1_2_066": {
        "preface": "(whimpering, blood pouring)",
        "options": ["Please... I only wanted to love you.","Rumi... help me... I did this for us..."]
    },
    "sub_branch1_2_067": {
        "options": ["This is how you showed love? By torturing an innocent woman and her unborn child to death?","Love? You don't know the meaning of the word."]
    },
    "sub_branch1_2_069": {
        "preface": "(raising hammer)",
        "options": ["One more, for our baby.","This last one is for the son you murdered."]
    },
    "sub_branch1_2_072": {
        "preface": "(whisper)",
        "options": ["Finally. Justice.","It's done. She can't hurt anyone anymore."]
    },
    "sub_branch1_2_075": {
        "preface": "(calmly)",
        "options": ["She killed my wife. She confessed everything before I stopped her.","Dr. Marzia Rahman murdered my wife three years ago. She came here tonight to kill me too."]
    },
    "sub_branch1_2_077": {
        "preface": "(complying)",
        "options": ["In her medical bag, you'll find drugs she was using to control me. In her apartment, there's evidence. She kept trophies from my wife's murder.","Check her apartment. She documented everything. Photos, journals, evidence of her obsession."]
    },
    "sub_branch1_2_080": {
        "options": ["What happens now?","Is this what you wanted? Justice?"]
    },
    "sub_branch1_2_085": {
        "options": ["I'm sorry I couldn't protect you both. But she can't hurt anyone anymore.","I failed you. I should have seen what she was. But justice has been served now."]
    },
    "sub_branch2_1_001": {
        "options": ["Marzia, how long were you outside before you knocked?","Tell me the truth. How long have you been watching my house?"]
    },
    "sub_branch2_1_002": {
        "preface": "(too casually)",
        "options": ["Just a few minutes. I was checking to see if your lights were on.","Not long. Wanted to make sure you were home before bothering you."]
    },
    "sub_branch2_1_003": {
        "options": ["From outside the window? Not from the front of the house?","You can see my lights from the front door. Why were you at the window?"]
    },
    "sub_branch2_1_005": {
        "options": ["I thought I saw you through the window and didn't want to disturb you if you were resting.","I was worried. Wanted to check on you without being intrusive."]
    },
    "sub_branch2_1_006": {
        "options": ["But you just said I wasn't answering the front door.","That doesn't make sense. You said you knocked and I didn't answer."]
    },
    "sub_branch2_1_008": {
        "preface": "(changing subject)",
        "options": ["How are you feeling today? I know anniversaries can be... difficult.","Let's not talk about this. How are you doing? Today must be hard."]
    },
    "sub_branch2_1_010": {
        "options": ["Have you been taking your medication regularly?","You're still on your prescriptions, right? Taking them as directed?"]
    },
    "sub_branch2_1_012": {
        "options": ["All of it? The mood stabilizers and the memory supplements?","Every pill? Including the ones I specifically prescribed for memory stabilization?"]
    },
    "sub_branch2_1_014": {
        "options": ["Marzia, why do I take medication for memory?","I've been meaning to ask - why exactly do I need those memory pills?"]
    },
    "sub_branch2_1_015": {
        "preface": "(clinical tone)",
        "options": ["Trauma can cause memory fragmentation. The medication helps prevent intrusive flashbacks and false memories from forming.","Severe grief can create false recollections. The medication keeps your memories stable and accurate."]
    },
    "sub_branch2_1_016": {
        "options": ["False memories of what?","What kind of false memories are you talking about?"]
    },
    "sub_branch2_1_017": {
        "preface": "(pause)",
        "options": ["Of things that might have been different. Ways you might have saved her. Your mind sometimes creates scenarios that didn't happen.","Guilt manifests as alternate timelines. Your brain tries to rewrite history. The pills prevent that."]
    },
    "sub_branch2_1_020": {
        "options": ["I've been having strange dreams lately.","Something's been happening. Dreams. Memories. I can't tell which is which anymore."]
    },
    "sub_branch2_1_021": {
        "preface": "(alert)",
        "options": ["What kind of dreams?","Tell me exactly what you've been seeing."]
    },
    "sub_branch2_1_022": {
        "options": ["About that night. About things I can't quite remember.","The accident. But the details are different from what you told me."]
    },
    "sub_branch2_1_024": {
        "options": ["Maybe we should adjust your dosage. Increase the memory stabilizers.","This is concerning. I think we need to up your medication immediately."]
    },
    "sub_branch2_1_025": {
        "options": ["Or maybe I should stop taking them altogether. See what I remember.","What if I just quit the pills? Let my mind clear naturally?"]
    },
    "sub_branch2_1_027": {
        "options": ["That would be very dangerous, Rumi. Some memories are suppressed for good reasons.","Absolutely not. The psychological damage could be catastrophic. Trust me on this."]
    },
    "sub_branch2_1_028": {
        "options": ["I was on the phone with the police earlier today. Just a follow-up call.","Interesting call I got today. Detective Hassan. Wanted to discuss Jannat's case."]
    },
    "sub_branch2_1_029": {
        "preface": "(trying to appear casual)",
        "options": ["Oh? About what?","Really? After three years? What did they want?"]
    },
    "sub_branch2_1_030": {
        "options": ["They told me something interesting. The case was never officially closed. Recently, they received an anonymous tip about another car being seen near Shyamoli Square that night.","Apparently new evidence surfaced. Witness reports of a second vehicle at the scene. They're reopening the investigation."]
    },
    "sub_branch2_1_032": {
        "options": ["That's impossible. It was a deserted road. It was raining. No one was there.","Can't be. I was... I mean, the reports said the area was completely empty."]
    },
    "sub_branch2_1_034": {
        "preface": "(voice dropping to whisper)",
        "options": ["How would you know no one was there, Marzia? The police report said you were on call at the hospital all night.","Funny thing, Marzia. You weren't at the scene. Or were you?"]
    },
    "sub_branch2_1_035": {
        "preface": "(forcing smile)",
        "options": ["Rumi, you're not making sense. The grief is making you paranoid. Maybe you should take your medication.","You're confused. The pills - you haven't been taking them regularly, have you? That's why you're having these delusions."]
    },
    "sub_branch2_1_036": {
        "options": ["Maybe I should call Detective Hassan right now. Ask him about that anonymous tip.","I have his direct number. Should I dial it? Get the details straight from him?"]
    },
    "sub_branch2_1_038": {
        "options": ["You don't want to do that, Rumi.","That would be a mistake. Trust me."]
    },
    "sub_branch2_1_039": {
        "options": ["Why not? What are you afraid they'll find?","Afraid of something, Marzia? Some truth coming to light?"]
    },
    "sub_branch2_1_040": {
        "preface": "(voice changing, becoming colder)",
        "options": ["I'm not afraid of anything. But you should be.","Fear? No. But you should be terrified of what happens next."]
    },
    "sub_branch2_1_043": {
        "preface": "(chilling smile)",
        "options": ["You were always smarter than she was.","I should have known you'd figure it out eventually. You're too clever for your own good."]
    },
    "sub_branch2_1_044": {
        "preface": "(standing)",
        "options": ["What did you just say?","What are you talking about?"]
    },
    "sub_branch2_1_045": {
        "options": ["Yes, I was there. I followed her. I watched her die. And I'm the one who made sure she died.","I killed her, Rumi. With these hands. And I'd do it again without hesitation."]
    },
    "sub_branch2_1_046": {
        "preface": "(barely breathing)",
        "options": ["You killed her.","You murdered my wife."]
    },
    "sub_branch2_1_047": {
        "preface": "(voice dripping venom)",
        "options": ["I corrected a cosmic error! I loved you! While you were wasting your life on her, I was building a career, making myself worthy of you!","She was holding you back! I set you free! Everything I did was for us!"]
    },
    "sub_branch2_1_049": {
        "options": ["She was a placeholder, and her time was up.","She was an obstacle. Nothing more. And obstacles must be removed."]
    },
    "sub_branch2_1_051": {
        "options": ["I lured her to the hospital parking garage. Told her I needed to give her a prenatal checkup.","It was so easy. A phone call about urgent test results. She came running."]
    },
    "sub_branch2_1_052": {
        "preface": "(shocked)",
        "options": ["Prenatal?","Wait... she was pregnant?"]
    },
    "sub_branch2_1_053": {
        "preface": "(theatrical gasp)",
        "options": ["Oh, did I forget to mention? She was pregnant, Rumi. Three months. She was going to tell you that night. She was carrying your son.","Surprise! You were going to be a father. She had a whole announcement planned. Pathetic, really."]
    },
    "sub_branch2_1_055": {
        "options": ["I couldn't let her have that. So I took this tire iron to her head. I destroyed her beautiful face so you would forget her faster.","A baby would have tied you to her forever. I couldn't allow that. So I bashed her skull in until she was unrecognizable."]
    },
    "sub_branch2_1_057": {
        "options": ["Then I drove her to Shyamoli Square and staged the crash. I am the author of your freedom, Rumi.","The car accident was my masterpiece. Every detail perfect. And you believed every word."]
    },
    "sub_branch2_1_058": {
        "preface": "(moving toward door)",
        "options": ["The pills I gave you weren't just for grief. They were to keep you in a fog. To keep you dependent. To keep you mine.","Three years of chemical control. You never suspected a thing. You were so beautifully compliant."]
    },
    "sub_branch2_1_060": {
        "options": ["I kept this as evidence of my devotion. I wanted it here tonight when you finally understood everything I've done for you.","This weapon is sacred. Her blood is still on it. Tonight, it becomes yours too."]
    },
    "sub_branch2_1_061": {
        "preface": "(backing away)",
        "options": ["You're insane.","You're a psychopath!"]
    },
    "sub_branch2_1_062": {
        "preface": "(screaming)",
        "options": ["I'M DEVOTED! And now you will finally thank me!","I'M IN LOVE! And you WILL appreciate my sacrifice!"]
    },
    "sub_branch2_1_065": {
        "preface": "(voice guttural through ruined lips)",
        "options": ["I'll kill you slowly! I'll peel the skin from your bones the way you've peeled it from my face!","You'll suffer! Every second of agony you've caused me, returned tenfold!"]
    },
    "sub_branch2_1_068": {
        "preface": "(choking on bone fragments)",
        "options": ["We... belong... together...","This... was... meant... to be..."]
    },
    "sub_branch2_1_070": {
        "preface": "(cornered, breaking chair leg)",
        "options": ["It's over, Marzia!","Stay back! Don't make me do this!"]
    },
    "sub_branch2_1_073": {
        "preface": "(dying whisper)",
        "options": ["I... only... wanted... you...","We... could have... been... perfect..."]
    },
    "sub_branch2_1_077": {
        "preface": "(simply)",
        "options": ["She killed my wife. She killed my baby.","Her confession is on the recording. She murdered Jannat and our unborn child."]
    },
    "sub_branch2_1_079": {
        "preface": "(complying)",
        "options": ["The recording has her confession. Check her apartment - she kept evidence.","It's all documented. The audio, the weapon, the trophies she kept. Check everything."]
    },
    "sub_branch2_1_090": {
        "preface": "(to gravestone)",
        "options": ["I know the truth now. All of it. About the baby, about what she did to you, about the three years of lies.","They told me everything. You were pregnant. You were coming home to tell me. And she stole it all."]
    },
    "sub_branch2_1_092": {
        "options": ["I'm sorry I couldn't protect you. I'm sorry I never knew about our child.","Forgive me. I was blind. I should have seen what she was doing."]
    },
    "sub_branch2_1_094": {
        "options": ["The truth is out now. She can't hurt anyone anymore. The whole world knows what she did.","Justice has been served. Your story is known. You can rest now."]
    },
    "sub_branch2_1_097": {
        "preface": "(whisper)",
        "options": ["Rest now. Both of you.","Sleep peacefully. I'll carry your memory with me always."]
    },
    "sub_branch2_2_001": {
        "preface": "(confused)",
        "options": ["Marzia? What are you doing here so late?","It's almost eight. Why are you here?"]
    },
    "sub_branch2_2_002": {
        "options": ["I was worried. Today is... well, you know what day it is.","The anniversary. I couldn't let you be alone tonight."]
    },
    "sub_branch2_2_005": {
        "options": ["I... I'm not sure. I was making tea and then... I think I heard something outside.","Something knocked over the kettle. I don't remember how."]
    },
    "sub_branch2_2_007": {
        "options": ["Rumi, have you been taking your medication?","Your pills. Tell me you've been taking them regularly."]
    },
    "sub_branch2_2_009": {
        "preface": "(concerned)",
        "options": ["You're having one of your episodes again, aren't you? You seem disoriented.","I can see it in your eyes. The fog. You're losing time again."]
    },
    "sub_branch2_2_010": {
        "preface": "(hollow voice)",
        "options": ["I'm fine. Just tired.","Nothing's wrong. Leave it alone."]
    },
    "sub_branch2_2_011": {
        "options": ["It's the anniversary. It's understandable that today would be difficult for you.","Three years today. The trauma resurfaces. It's normal."]
    },
    "sub_branch2_2_013": {
        "options": ["But you need to take your medication, Rumi. It helps keep the bad memories from overwhelming you.","These pills are essential. They protect you from the worst of what happened."]
    },
    "sub_branch2_2_014": {
        "preface": "(frowning, memory gaps troubling him)",
        "options": ["Marzia, that night... the night of the accident. I was home, right?","Something's bothering me. Where was I when Jannat died?"]
    },
    "sub_branch2_2_015": {
        "preface": "(voice slightly too quick)",
        "options": ["Yes, of course. You were here, asleep. The police called you, then you called me in a panic.","Home in bed. You got the call around 3 AM. You were hysterical."]
    },
    "sub_branch2_2_016": {
        "options": ["I remember the morgue. But everything before that is... blank.","The hospital is clear in my mind. But earlier that night... nothing."]
    },
    "sub_branch2_2_017": {
        "preface": "(handing him pills and water)",
        "options": ["It's a trauma response. Your mind is protecting you from the pain.","Dissociative amnesia. The brain's defense mechanism against unbearable trauma."]
    },
    "sub_branch2_2_020": {
        "preface": "(suddenly)",
        "options": ["Marzia, that night... the night of the accident. I was home, right? You came and got me.","Tell me again. Every detail. Where was I that night?"]
    },
    "sub_branch2_2_021": {
        "preface": "(voice slightly too quick)",
        "options": ["Yes, of course. You were here, asleep. The police called you, then you called me in a panic. I drove you to the hospital.","Safe at home. Sleeping soundly until the call came. I drove you to identify the body."]
    },
    "sub_branch2_2_022": {
        "options": ["I remember the morgue. But everything before that is... blank. A fog.","Pulling back the sheet - that I remember. But the hours before... nothing."]
    },
    "sub_branch2_2_023": {
        "preface": "(handing him pills and water)",
        "options": ["It's a trauma response. Your mind is protecting you from the pain. It's for the best.","Selective amnesia. Your psyche shielding itself. Don't fight it."]
    },
    "sub_branch2_2_029": {
        "preface": "(gasping)",
        "options": ["The wallpaper.","We changed the wallpaper. Why?"]
    },
    "sub_branch2_2_030": {
        "preface": "(sharp with alarm)",
        "options": ["Rumi? What is it? You're pale as a sheet.","What's wrong? You look like you're about to pass out."]
    },
    "sub_branch2_2_031": {
        "preface": "(staring at living room wall)",
        "options": ["We painted over the wallpaper in the bedroom. Why did we do that?","The bedroom. We repainted it. Right after... why?"]
    },
    "sub_branch2_2_032": {
        "preface": "(eyes darting nervously)",
        "options": ["It was old. You wanted a change after... after she was gone. To help you move on.","Fresh start. You needed to erase reminders. Standard grief response."]
    },
    "sub_branch2_2_033": {
        "preface": "(standing up)",
        "options": ["No. We painted it to cover the bloodstains.","Blood. There was blood on those walls. Her blood."]
    },
    "sub_branch2_2_035": {
        "options": ["Rumi, you're not thinking clearly! You're having a psychotic break!","Stop this! The medication is wearing off and you're hallucinating!"]
    },
    "sub_branch2_2_038": {
        "preface": "(choked whisper, turning to face Marzia)",
        "options": ["I didn't just kill her. I killed him too. What did we do with his body, Marzia?","Two bodies. Not one. Him and Jannat. Where did you help me hide him?"]
    },
    "sub_branch2_2_039": {
        "preface": "(face crumpling, lie no longer sustainable)",
        "options": ["We staged it. Her on the street, him in J-Block. I helped you. You weren't... you weren't yourself.","The construction site. J-Block foundation. Before the concrete pour. He's still there."]
    },
    "sub_branch2_2_040": {
        "options": ["I did it to protect you!","You helped me commit murder!"]
    },
    "sub_branch2_2_042": {
        "preface": "(knuckles white on sledgehammer handle)",
        "options": ["You let me believe I was a victim.","Three years of lies. You made me think I was the grieving husband."]
    },
    "sub_branch2_2_043": {
        "preface": "(sobbing)",
        "options": ["I love you! I've always loved you. I couldn't let them send you to prison!","What was I supposed to do? Turn in the man I've loved since childhood?"]
    },
    "sub_branch2_2_045": {
        "options": ["I did what I had to do!","My choices saved your life!"]
    },
    "sub_branch2_2_046": {
        "options": ["You didn't want me to heal. You wanted me broken so you could hold the pieces together.","This wasn't love. This was control. You kept me sedated and dependent."]
    },
    "sub_branch2_2_048": {
        "options": ["What now, Rumi? We can go on as we have. I can increase the dosage. You can forget again.","We have a choice. More medication. Deeper suppression. You never have to remember."]
    },
    "sub_branch2_2_050": {
        "options": ["No more lies.","I'm done living in your manufactured reality."]
    },
    "sub_branch2_2_051": {
        "preface": "(panicked)",
        "options": ["Please, Rumi. Think about what you're doing. We've kept this secret for three years. We can keep it forever.","Don't be stupid. Three years without suspicion. We're safe. Stay safe with me."]
    },
    "sub_branch2_2_053": {
        "preface": "(more to himself)",
        "options": ["I killed them both. I came home early. I heard them in our bedroom...","I murdered my wife and her lover. In our bed. In our home."]
    },
    "sub_branch2_2_055": {
        "options": ["Rumi! I can explain—","Wait! This isn't what it looks like!"]
    },
    "sub_branch2_2_056": {
        "preface": "(voice shaking with rage)",
        "options": ["How long?","Tell me everything. Now."]
    },
    "sub_branch2_2_057": {
        "preface": "(climbing out of bed)",
        "options": ["Six months. I'm pregnant, Rumi. It's his child.","We've been together since last summer. The baby I'm carrying - it's his."]
    },
    "sub_branch2_2_058": {
        "preface": "(standing)",
        "options": ["Look, man, we didn't mean for you to find out this way—","Listen, we were going to tell you. We're in love."]
    },
    "sub_branch2_2_060": {
        "preface": "(pleading)",
        "options": ["Rumi, please! We can work this out!","Don't do this! We can talk! Please!"]
    },
    "sub_branch2_2_062": {
        "preface": "(screaming, running)",
        "options": ["NO! RUMI, NO!","STOP! OH GOD, PLEASE STOP!"]
    },
    "sub_branch2_2_064": {
        "preface": "(tears streaming)",
        "options": ["She told me she was pregnant with his child. That they were starting a new life together.","Six months. They'd been together six months. The baby wasn't mine."]
    },
    "sub_branch2_2_065": {
        "preface": "(step toward him)",
        "options": ["She betrayed you. She deserved what she got.","She made her choice. You responded with justified rage."]
    },
    "sub_branch2_2_066": {
        "preface": "(sharp accusation)",
        "options": ["And what did you deserve, Marzia? You didn't call the police. You didn't try to stop me. You helped me. Why?","You're complicit. An accessory. Why did you protect me?"]
    },
    "sub_branch2_2_067": {
        "preface": "(complex emotion - devotion and possession)",
        "options": ["Because I've loved you since we were children. I watched you waste that love on her, and she repaid you with betrayal.","I've waited my whole life for you. She took what should have been mine. Her death was... convenient."]
    },
    "sub_branch2_2_068": {
        "options": ["So you saw an opportunity.","You used my crime to bind me to you."]
    },
    "sub_branch2_2_069": {
        "options": ["I saw a chance to save you! I knew how to make it look like an accident. I knew how to help you forget.","I saved your life! The staging, the medication, the false memories - all of it kept you free!"]
    },
    "sub_branch2_2_070": {
        "preface": "(bitter laugh)",
        "options": ["You didn't want me to forget to heal me. You wanted me to forget so I'd be dependent on you.","This was never about helping me. It was about owning me."]
    },
    "sub_branch2_2_071": {
        "options": ["What did we do with their bodies? Tell me everything. No more sedatives, no more half-truths.","Every detail. The staging, the disposal, the cover-up. I need to know it all."]
    },
    "sub_branch2_2_073": {
        "options": ["You killed them both in here. He died first - one blow to the temple. But Jannat... she tried to run. You caught her in the hallway.","The man was instant. Skull fracture, brain hemorrhage. Dead before he hit the floor. Jannat fought. She made it to the hallway before you caught her."]
    },
    "sub_branch2_2_075": {
        "options": ["Multiple blunt force traumas to the cranium. Catastrophic brain injury. Death was immediate.","Seventeen separate impacts. The skull was completely shattered. She died on the fourth blow, but you didn't stop."]
    },
    "sub_branch2_2_076": {
        "options": ["And then I called you.","I called you from this room, covered in their blood."]
    },
    "sub_branch2_2_077": {
        "options": ["You were incoherent. Covered in blood. I came immediately. I knew what to do.","11:47 PM. You were sobbing, couldn't form complete sentences. I arrived within twenty minutes."]
    },
    "sub_branch2_2_079": {
        "options": ["I cleaned you up first. Then we wrapped his body in plastic from the garage. Put him in my car trunk.","Shower first, to clear your head and remove evidence. Then we dealt with the bodies systematically."]
    },
    "sub_branch2_2_080": {
        "options": ["And Jannat?","What about my wife?"]
    },
    "sub_branch2_2_081": {
        "options": ["We made it look like she'd been in his car. Like they were running away together and crashed. I used my medical knowledge to ensure the injuries matched a high-speed collision.","The car accident was my design. Positioned the body, created secondary trauma consistent with vehicular impact. No one questioned it."]
    },
    "sub_branch2_2_083": {
        "options": ["I'm not a grieving widower. I'm a murderer.","Everything I believed about myself... it's all lies. I'm a monster."]
    },
    "sub_branch2_2_084": {
        "preface": "(desperate)",
        "options": ["We can increase your medication. You can forget again. We can move away, start fresh.","More pills, stronger doses. I can make this go away again. We can be happy."]
    },
    "sub_branch2_2_085": {
        "options": ["Did you ever feel guilt? Even once in three years?","How do you live with this? How do you sleep?"]
    },
    "sub_branch2_2_086": {
        "options": ["Guilt? For what? For protecting you? For loving you enough to save you from yourself?","I saved your life. I gave you three more years of freedom. That's not something to feel guilty about."]
    },
    "sub_branch2_2_088": {
        "preface": "(quietly, reaching for phone)",
        "options": ["I'm calling the police.","This ends now. I'm confessing everything."]
    },
    "sub_branch2_2_089": {
        "preface": "(lunging, knocking phone away)",
        "options": ["You can't! I won't let you throw everything away!","NO! I didn't sacrifice everything for you to destroy it now!"]
    },
    "sub_branch2_2_095": {
        "preface": "(dialing)",
        "options": ["Emergency services.","Police. I need police."]
    },
    "sub_branch2_2_097": {
        "preface": "(voice steady)",
        "options": ["I need to report a murder. Three murders, actually.","I'm confessing to homicide. Multiple victims over three years."]
    },
    "sub_branch2_2_104": {
        "preface": "(to himself)",
        "options": ["The truth of what I did will haunt me until I die. But the truth is better than the comfortable lie.","I killed three people. I deserve everything that's coming. At least now I'm not living in a fog."]
    }
};

if (typeof module !== "undefined" && module.exports) {
    module.exports = DIALOGUE_OPTIONS;
}
